name: Build (Reusable)

on:
  workflow_call:
    inputs: &workflow-inputs
      debug:
        description: Set build configuration to `Debug` when true.
        required: false
        default: false
        type: boolean
      native:
        description: Build native artifacts when true.
        required: false
        default: false
        type: boolean
  workflow_dispatch: 
    inputs: *workflow-inputs

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        type:
          - normal
          - trimmed
        arch:
          - win-x86
          - win-x64
          - win-arm64
          - linux-x64
          - linux-arm64
          - osx-x64
          - osx-arm64

    name: Build ${{ matrix.type }} ${{ matrix.arch }}
    runs-on: ubuntu-latest

    steps: &build-steps
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.4.0
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: >-
          dotnet publish FlowLauncher/FlowLauncher.csproj
          -p:PublishType=${{ matrix.type }}
          -p:RuntimeIdentifier=${{ matrix.arch }}
          ${{ inputs.debug && '-p:Configuration=Debug' || '' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: FlowLauncher_${{ matrix.type }}_${{ matrix.arch }}${{ inputs.debug && '_debug' || '' }}
          path: FlowLauncher/bin/${{ inputs.debug && 'Debug' || 'Release' }}/net10.0/${{ matrix.arch }}/publish/
          if-no-files-found: error

  build-native:
    if: inputs.native
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: win-x86
            type: native
            runs-on: windows-latest
          - arch: win-x64
            type: native
            runs-on: windows-latest
          - arch: win-arm64
            type: native
            runs-on: windows-11-arm
          - arch: linux-x64
            type: native
            runs-on: ubuntu-latest
          - arch: linux-arm64
            type: native
            runs-on: ubuntu-24.04-arm
          - arch: osx-x64
            type: native
            runs-on: macos-latest
          - arch: osx-arm64
            type: native
            runs-on: macos-latest

    name: Build native ${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}
    steps: *build-steps
