name: Publish (Nightly)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE*'
      - 'docs/**'
      - 'LICENSE*'

jobs:
  publish-nightly:
    uses: ./.github/workflows/publish-reusable.yml
    with:
      debug: true
      version: 0.0.${{ github.run_number }}
